version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - graphviz
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Install regular dependencies.
# Then, install special pinning for RTD.
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf
