# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
     branches: # only build on PRs against 'main' if you need to further limit when CI is run.
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  ci_tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@924441154cf3053034c6513d5e06c69d262fb9a6  # v1.13.0
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      submodules: false
      coverage: ''
      envs: |
        #- name: Python 3.12 with minimal dependencies and full coverage
        #  linux: py312-test-cov
        #  coverage: codecov

        - name: Code style checks
          linux: codestyle

        - name: Link checks
          linux: linkcheck

        - name: OS X - Python 3.13 with minimal dependencies
          macos: py313-test
          runs-on: macos-latest

        - name: Windows - Python 3.11 with all optional dependencies
          windows: py311-test-alldeps
          toxargs: -v

        - name: Python 3.12 with remote data, all dependencies, and coverage
          linux: py312-test-alldeps-cov
          toxargs: -v
          posargs: --remote-data=any

        - name: Python 3.11 with oldest version of key dependencies
          linux: py311-test-oldestdeps

  allowed_failures:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@924441154cf3053034c6513d5e06c69d262fb9a6  # v1.13.0
    with:
      submodules: false
      coverage: ''
    name: ${{ matrix.name }}
      envs: |
        - name: (Allowed Failure) Python 3.13 with latest dev versions of key dependencies
          linux: py313-test-devdeps
          posargs: --verbose
